// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvX7D0JuzrO8C-TCCj-3oaElX-7AxjH10',
    appId: '1:1097559465613:web:93fdaa095ab9f2a8d34cc4',
    messagingSenderId: '1097559465613',
    projectId: 'app1-657b5',
    authDomain: 'app1-657b5.firebaseapp.com',
    storageBucket: 'app1-657b5.appspot.com',
    measurementId: 'G-FGDMF3RN2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBshWvW0KHULiycRimo2Vo05JVb-GD5vC0',
    appId: '1:1097559465613:android:283bb0e2f39b6f98d34cc4',
    messagingSenderId: '1097559465613',
    projectId: 'app1-657b5',
    storageBucket: 'app1-657b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe2UA3npnForRqjxL_jIvrjGjlBttbfy0',
    appId: '1:1097559465613:ios:bbf9c79e754371e2d34cc4',
    messagingSenderId: '1097559465613',
    projectId: 'app1-657b5',
    storageBucket: 'app1-657b5.appspot.com',
    iosBundleId: 'com.aizaz.top.bbc.flutterNewsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe2UA3npnForRqjxL_jIvrjGjlBttbfy0',
    appId: '1:1097559465613:ios:00dc44bfb3f8ff4ad34cc4',
    messagingSenderId: '1097559465613',
    projectId: 'app1-657b5',
    storageBucket: 'app1-657b5.appspot.com',
    iosBundleId: 'com.example.myNewsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvX7D0JuzrO8C-TCCj-3oaElX-7AxjH10',
    appId: '1:1097559465613:web:2a52aab7c1ee851bd34cc4',
    messagingSenderId: '1097559465613',
    projectId: 'app1-657b5',
    authDomain: 'app1-657b5.firebaseapp.com',
    storageBucket: 'app1-657b5.appspot.com',
    measurementId: 'G-EP3X96CW5T',
  );
}
